training:
  batch_size: 64
  queue_size: 60000
  n_epochs: 500000
  n_iters: 300001
  snapshot_freq: 3000
  sample_size: 9
  snapshot_sampling: true
  anneal_power: 2
  log_all_sigmas: false
  k: 64
  epsilon: 10

sampling:
  batch_size: 64
  data_init: false
  step_lr: 0.0000033
  n_steps_each: 5
  ckpt_id: 210000
  final_only: true
  fid: false
  denoise: true
  num_samples4fid: 10000
  inpainting: false
  interpolation: false
  n_interpolations: 15
  private_attribute: smile

fast_fid:
  batch_size: 1024
  num_samples: 1028
  step_lr: 0.0000033
  n_steps_each: 5
  begin_ckpt: 300000
  end_ckpt: 300000
  verbose: false
  ensemble: false

test:
  begin_ckpt: 5000
  end_ckpt: 210000
  batch_size: 100

data:
  dataset: "CUB"
  image_size: 64
  channels: 3
  logit_transform: false
  uniform_dequantization: false
  gaussian_dequantization: false
  random_flip: true
  rescaled: false
  num_workers: 32 # for testing
  privacy_eval : True

model:
  sigma_begin: 90
  num_classes: 500
  ema: true
  ema_rate: 0.999
  spec_norm: false
  sigma_dist: geometric
  sigma_end: 0.01
  normalization: InstanceNorm++
  nonlinearity: elu
  ngf: 128

optim:
  weight_decay: 0.000
  optimizer: "Adam"
  lr: 0.0001
  beta1: 0.9
  amsgrad: false
  eps: 0.00000001
